### ISSUE TITLE
[Bare Minimum] todo 추가 기능 구현

### ISSUE THREAD

**Issue by JoeunNAL** [JoeunNAL/todo-app-codestates#1]
* [ ] 태그를 설정할 수 있다.
* [ ] 버튼을 클릭하여 추가한다.
* [x] 체크 표시를 추가하여 해야할 일과 한 일을 구분할 수 있다.
